import Link from "next/link";
import { notFound } from "next/navigation";
import { Button, Card, Input, Label, SectionHeader, Textarea } from "@/components/ui";
import { prisma } from "@/lib/db";
import { requireSession } from "@/lib/require";
import { atLeastLevel, getEffectivePermissions } from "@/lib/permissions";
import { updateStudentAction } from "../../actions";
import { ParentAddressField } from "@/components/parent-address-field";
import { getSchoolStudentDemographicsConfig } from "@/lib/student-demographics";

function dateValue(d: Date | null | undefined) {
  if (!d) return "";
  return d.toISOString().slice(0, 10);
}

export default async function EditStudentPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession();
  const perms = await getEffectivePermissions({
    schoolId: session.schoolId,
    userId: session.userId,
    roleId: session.roleId
  });
  const canEditStudents = perms["STUDENTS"] ? atLeastLevel(perms["STUDENTS"], "EDIT") : false;
  const { id } = await params;

  const student = await prisma.student.findFirst({
    where:
      canEditStudents
        ? { id, schoolId: session.schoolId }
        : {
            id,
            schoolId: session.schoolId,
            parents: { some: { userId: session.userId } }
          },
    include: { class: true }
  });
  if (!student) return notFound();
  const demographicsConfig = await getSchoolStudentDemographicsConfig(session.schoolId);

  return (
    <div className="space-y-5 animate-fade-up">
      <Link href={`/students/${student.id}`} className="inline-flex items-center gap-1.5 text-sm text-white/40 hover:text-white/75 transition">
        ← Back to student
      </Link>
      <SectionHeader
        title={canEditStudents ? "Edit Student" : "Update Parent & Guardian Details"}
        subtitle={canEditStudents ? "Update student, parent, and guardian information" : "Parents can update contact and guardian information"}
      />

      <Card>
        <form action={updateStudentAction} className="grid grid-cols-1 md:grid-cols-2 gap-5">
          <input type="hidden" name="id" value={student.id} />

          {canEditStudents ? (
          <div className="md:col-span-2">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-white/35 mb-3">Identity</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label required>Student ID</Label>
                <Input defaultValue={student.studentId} disabled className="bg-white/[0.08] text-white/50 border-white/[0.08]" />
              </div>
              <div>
                <Label>Admission number</Label>
                <Input defaultValue={student.admissionNo ?? ""} disabled className="bg-white/[0.08] text-white/50 border-white/[0.08]" />
              </div>
              <div className="md:col-span-2">
                <Label required>Full name</Label>
                <Input name="fullName" defaultValue={student.fullName} required />
              </div>
            </div>
          </div>
          ) : null}

          {canEditStudents ? (
          <div className="md:col-span-2 pt-3 border-t border-white/[0.07]">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-white/35 mb-3">Academic & Contact</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <Label>Class</Label>
                <Input name="className" defaultValue={student.class?.name ?? ""} placeholder="Grade 6" />
              </div>
              <div>
                <Label>Section</Label>
                <Input name="section" defaultValue={student.class?.section ?? ""} placeholder="A" />
              </div>
              <div>
                <Label>Roll number</Label>
                <Input defaultValue={student.rollNumber ?? "Auto-generated"} disabled className="bg-white/[0.08] text-white/50 border-white/[0.08]" />
                <p className="mt-1 text-[11px] text-white/35">Auto-generated by class strength.</p>
              </div>
              <div>
                <Label>Gender</Label>
                <select
                  name="gender"
                  defaultValue={student.gender ?? ""}
                  className="w-full rounded-[13px] bg-black/25 border border-white/[0.09] px-3.5 py-2.5 text-base sm:text-sm text-white outline-none"
                >
                  <option value="">Select gender</option>
                  {demographicsConfig.genders.map((gender) => (
                    <option key={gender} value={gender}>{gender}</option>
                  ))}
                </select>
              </div>
              <div>
                <Label>Date of birth</Label>
                <Input name="dateOfBirth" type="date" defaultValue={dateValue(student.dateOfBirth)} />
              </div>
              <div>
                <Label>Blood group</Label>
                <select
                  name="bloodGroup"
                  defaultValue={student.bloodGroup ?? ""}
                  className="w-full rounded-[13px] bg-black/25 border border-white/[0.09] px-3.5 py-2.5 text-base sm:text-sm text-white outline-none"
                >
                  <option value="">Select blood group</option>
                  {demographicsConfig.bloodGroups.map((group) => (
                    <option key={group} value={group}>{group}</option>
                  ))}
                </select>
              </div>
              <div className="md:col-span-3">
                <Label>Address</Label>
                <Textarea name="address" rows={2} defaultValue={student.address ?? ""} />
              </div>
              <div>
                <Label>Transport</Label>
                <Input name="transportDetails" defaultValue={student.transportDetails ?? ""} />
              </div>
              <div className="md:col-span-2">
                <Label>Medical notes</Label>
                <Textarea name="medicalNotes" rows={2} defaultValue={student.medicalNotes ?? ""} />
              </div>
            </div>
          </div>
          ) : null}

          <div className="md:col-span-2 pt-3 border-t border-white/[0.07]">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-white/35 mb-3">Parent Details</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label>Father's name</Label>
                <Input name="fatherName" defaultValue={student.fatherName ?? ""} />
              </div>
              <div>
                <Label>Mother's name</Label>
                <Input name="motherName" defaultValue={student.motherName ?? ""} />
              </div>
              <div>
                <Label>Mobile(s)</Label>
                <Input name="parentMobiles" defaultValue={student.parentMobiles ?? ""} placeholder="Comma-separated" />
              </div>
              <div>
                <Label>Email(s)</Label>
                <Input name="parentEmails" defaultValue={student.parentEmails ?? ""} placeholder="Comma-separated" />
              </div>
              <div>
                <Label>Occupation</Label>
                <Input name="parentOccupation" defaultValue={student.parentOccupation ?? ""} />
              </div>
              <div>
                <Label>Emergency contact</Label>
                <Input name="emergencyContact" defaultValue={student.emergencyContact ?? ""} />
              </div>
              <ParentAddressField studentAddress={student.address} parentAddress={student.parentAddress} />
            </div>
          </div>

          <div className="md:col-span-2 pt-3 border-t border-white/[0.07]">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-white/35 mb-3">Guardian Details</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label>Guardian name</Label>
                <Input name="guardianName" defaultValue={student.guardianName ?? ""} />
              </div>
              <div>
                <Label>Relationship</Label>
                <Input name="guardianRelationship" defaultValue={student.guardianRelationship ?? ""} />
              </div>
              <div>
                <Label>Guardian mobile</Label>
                <Input name="guardianMobile" defaultValue={student.guardianMobile ?? ""} />
              </div>
              <div>
                <Label>Alternate contact</Label>
                <Input name="guardianAltContact" defaultValue={student.guardianAltContact ?? ""} />
              </div>
              <div className="md:col-span-2">
                <Label>Guardian address</Label>
                <Textarea name="guardianAddress" rows={2} defaultValue={student.guardianAddress ?? ""} />
              </div>
              <div className="md:col-span-2">
                <Label>Pickup authorization details</Label>
                <Textarea name="pickupAuthDetails" rows={2} defaultValue={student.pickupAuthDetails ?? ""} />
              </div>
            </div>
          </div>

          <div className="md:col-span-2 pt-3 border-t border-white/[0.07] flex items-center justify-between">
            <Link href={`/students/${student.id}`}>
              <Button variant="ghost" type="button">Cancel</Button>
            </Link>
            <Button type="submit">Save changes →</Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
